<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $libri = [
            [
                'cover' => 'https://cdn.kobo.com/book-images/c9472126-7f96-402d-ba57-5ba4c0f4b238/353/569/90/False/nineteen-eighty-four-1984-george.jpg',
                'color' =>'#D21116',
                'title' => '1984',
                'released' => '1949-06-08',
                'publisher' => 'Secker & Warburg',
                'plot' => '1984 è un romanzo distopico di George Orwell pubblicato nel 1949. La storia è ambientata in un futuro distopico, in un mondo totalitario diviso in tre superstati.',
                'isbn' => 9780151010264,
                'author' => 1,
                'genre' => 1,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71rfLwvICQL._SL1500_.jpg',
                'color' => '#5AC5F3',
                'title' => 'Animal Farm',
                'released' => '1945-08-17',
                'publisher' => 'Secker & Warburg',
                'plot' => 'Animal Farm è un romanzo satirico di George Orwell pubblicato nel 1945. Il libro riflette gli eventi che portarono alla Rivoluzione Russa e all\'era stalinista dell\'Unione Sovietica.',
                'isbn' => 9788807882101,
                'author' => 1,
                'genre' => 1,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71EoYkXesEL._SL1500_.jpg',
                'color' => '#6D6842',
                'title' => 'Orgoglio e Pregiudizio',
                'released' => '1813-01-28',
                'publisher' => 'T. Egerton, Whitehall',
                'plot' => 'Orgoglio e pregiudizio è un romanzo di Jane Austen, pubblicato nel 1813. È considerato uno dei capolavori della letteratura inglese e un classico della letteratura mondiale.',
                'isbn' => 9788804681452,
                'author' => 2,
                'genre' => 8,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81s2Njtv2oL._SL1500_.jpg
                ',
                'color' => '#364130',
                'title' => 'Emma',
                'released' => '1815-12-23',
                'publisher' => 'John Murray',
                'plot' => 'Emma è un romanzo di Jane Austen, pubblicato nel 1815. È un romanzo di crescita personale, ambientato nel periodo georgiano, e descrive la vita e le preoccupazioni di giovani donne in Inghilterra.',
                'isbn' => 9788804622684,
                'author' => 2,
                'genre' => 8,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81uod0Mf4KL._SL1500_.jpg
                ',
                'color' => '#F70200',
                'title' => 'Harry Potter e la Pietra Filosofale',
                'released' => '1997-06-26',
                'publisher' => 'Bloomsbury',
                'plot' => 'Harry Potter e la Pietra Filosofale è il primo libro della serie di Harry Potter di J.K. Rowling. Il romanzo segue le avventure di Harry Potter, un giovane mago, e dei suoi amici Hermione Granger e Ron Weasley, durante il loro primo anno alla Scuola di Magia e Stregoneria di Hogwarts.',
                'isbn' => 9780747532743,
                'author' => 3,
                'genre' => 2,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/716aYxhlUiL._SL1500_.jpg',
                'color' => '#C39B55',
                'title' => 'Harry Potter e la Camera dei Segreti',
                'released' => '1998-07-02',
                'publisher' => 'Bloomsbury',
                'plot' => 'Harry Potter e la Camera dei Segreti è il secondo libro della serie di Harry Potter di J.K. Rowling. La trama segue le avventure di Harry Potter, un giovane mago, e dei suoi amici Hermione Granger e Ron Weasley, durante il loro secondo anno alla Scuola di Magia e Stregoneria di Hogwarts.',
                'isbn' => 9780747538493,
                'author' => 3,
                'genre' => 2,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81sqPftaizL._SL1500_.jpg',
                'color' => '#929292',
                'title' => 'Addio alle armi',
                'released' => '1929-10-05',
                'publisher' => 'Charles Scribner\'s Sons',
                'plot' => 'Addio alle armi è un romanzo di Ernest Hemingway pubblicato nel 1929. Ambientato durante la prima guerra mondiale, il romanzo narra la storia di un giovane tenente americano che si innamora di un\'infermiera britannica durante il conflitto.',
                'isbn' => 9788845282404,
                'author' => 4, 
                'genre' => 4, 
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81Q5sYM4mQL._SL1500_.jpg',
                'color' => '#5483B9',
                'title' => 'Il vecchio e il mare',
                'released' => '1952-09-01',
                'publisher' => 'Charles Scribner\'s Sons',
                'plot' => 'Il vecchio e il mare è un romanzo di Ernest Hemingway pubblicato nel 1952. Il romanzo narra la storia di un anziano pescatore cubano e del suo lungo e solitario sforzo per catturare un gigantesco marlin nel Golfo del Messico.',
                'isbn' => 9788804482104,
                'author' => 4, 
                'genre' => 7, 
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71oWFPril4L._AC_UF1000,1000_QL80_.jpg',
                'color' => '#A41B23',
                'title' => 'It',
                'released' => '1986-09-15',
                'publisher' => 'Viking Press',
                'plot' => 'It è un romanzo horror di Stephen King pubblicato nel 1986. Il libro segue le vicende di un gruppo di bambini chiamati il "Club dei Perdenti" e le loro avventure con una creatura demoniaca che si manifesta principalmente sotto forma di un clown chiamato Pennywise.',
                'isbn' => 9780670813025,
                'author' => 5, 
                'genre' => 6, 
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/61JZ-er-i5L._AC_UF1000,1000_QL80_.jpg',
                'color' => '#533D25',
                'title' => 'Il miglio verde',
                'released' => '1996-08-28',
                'publisher' => 'Scribner',
                'plot' => 'Il miglio verde è un romanzo di Stephen King pubblicato nel 1996. La storia è ambientata nella sezione E del braccio di morte della prigione di Cold Mountain negli anni \'30 e segue la vita dei detenuti e dei guardie carcerarie che vivono e lavorano lì.',
                'isbn' => 9788807812245,
                'author' => 5, 
                'genre' => 6, 
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/517LFQ4m0DL.jpg',
                'color' => '#1D2248',
                'title' => 'Assassinio sull\'Orient Express',
                'released' => '1934-01-01',
                'publisher' => 'Collins Crime Club',
                'plot' => 'Assassinio sull\'Orient Express è un romanzo giallo di Agatha Christie pubblicato nel 1934. Il detective Hercule Poirot indaga su un omicidio avvenuto sul celebre treno Orient Express.',
                'isbn' => 9780062073501,
                'author' => 6, 
                'genre' => 4, 
            ],
            [
                'cover' => 'https://www.ibs.it/images/8054317086907_0_536_0_75.jpg',
                'color' => '#C93430',
                'title' => 'E poi non ne rimase nessuno',
                'released' => '1939-11-06',
                'publisher' => 'Collins Crime Club',
                'plot' => 'E poi non ne rimase nessuno è un romanzo giallo di Agatha Christie pubblicato nel 1939. Il romanzo segue le vicende di dieci personaggi invitati su un\'isola al largo della costa del Devon e misteriosamente uccisi uno dopo l\'altro.',
                'isbn' => 9788804685405,
                'author' => 6, 
                'genre' => 4, 
            ],
            [
                'cover' => 'https://cs.ilgiardinodeilibri.it/data/prod/orig/c/cinquanta-sfumature-grigio-2014.jpg?_=1594027950',
                'color' => '#4E667F',
                'title' => 'Cinquanta sfumature di grigio',
                'released' => '2011-06-20',
                'publisher' => 'Arrow Books',
                'plot' => 'Cinquanta sfumature di grigio è il primo romanzo della trilogia di E.L. James. La storia segue la relazione tra Anastasia Steele, una giovane studentessa universitaria, e Christian Grey, un affascinante e misterioso imprenditore.',
                'isbn' => 9788865085059,
                'author' => 7, 
                'genre' => 5, 
            ],
            [
                'cover' => 'https://www.oscarmondadori.it/content/uploads/2020/04/978880472929HIG-310x480.jpg?x89969',
                'color' => '#041C31',
                'title' => 'Cinquanta sfumature di nero',
                'released' => '2012-04-17',
                'publisher' => 'Arrow Books',
                'plot' => 'Cinquanta sfumature di nero è il secondo romanzo della trilogia di E.L. James. Il libro continua a seguire la relazione tra Anastasia Steele e Christian Grey mentre affrontano nuove sfide e segreti del loro passato.',
                'isbn' => 9788865088234,
                'author' => 7, 
                'genre' => 5, 
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/71FZDMfeF6L._SY466_.jpg',
                'color' => '#a22720',
                'title' => 'Sulla strada',
                'released' => '1957-09-05',
                'publisher' => 'Viking Press',
                'plot' => 'Sal Paradise, un giovane scrittore, incontra Dean Moriarty, un carismatico e impulsivo ex detenuto, a New York. I due si legano immediatamente e decidono di intraprendere un viaggio attraverso il paese in cerca di avventure, libertà e significato.',
                'isbn' => 9780140042597,
                'author' => 17, 
                'genre' => 5, 
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/61YrFZdddRL._SY466_.jpg',
                'color' => '#594679',
                'title' => 'I vagabondi del Dharma',
                'released' => '1958-07-21',
                'publisher' => 'Penguin',
                'plot' => 'Il romanzo racconta le esperienze di Kerouac sulla West Coast americana e in particolare del suo avvicinamento al Buddhismo, alla filosofia Zen e al Trascendentalismo.',
                'isbn' => 9780241348062,
                'author' => 17, 
                'genre' => 5, 
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/718AI4cEYsL._SL1500_.jpg',
                'color' => '#e98f3a',
                'title' => 'La città e la metropoli',
                'released' => '1950-02-01',
                'publisher' => 'Harcourt Brace',
                'plot' => 'Due brevi racconti che mettono a confronto la vita nei quartieri cittadini, catturando frenesia ed energia delle strade e degli incontri casuali.',
                'isbn' => 9788804661283,
                'author' => 17, 
                'genre' => 5, 
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/81hxQ+DlE3L._SL1500_.jpg',
                'color' => '#5789ba',
                'title' => 'Big Sur',
                'released' => '1962-01-01',
                'publisher' => 'Chronicle Books',
                'plot' => 'Il romanzo segue il personaggio di Jack Duluoz (alter ego di Kerouac) mentre cerca fuga e isolamento nella bellezza naturale di Big Sur, solo per essere affrontato dai propri demoni interiori e ansia.',
                'isbn' => 9780140168129,
                'author' => 17, 
                'genre' => 5, 
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/81FFaSQRPTL._SL1500_.jpg',
                'color' => '#94786d',
                'title' => 'I sotterranei',
                'released' => '1958-01-01',
                'publisher' => 'Grove Press',
                'plot' => 'Il protagonista Leo Percepied, basato su Kerouac stesso, si innamora di Mardou Fox, una donna afroamericana. Il romanzo esplora temi di amore, identità e le sfide delle relazioni interrazziali negli USA degli anni 50.',
                'isbn' => 9780345271303,
                'author' => 17, 
                'genre' => 5, 
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/61Po8tew53L._SY522_.jpg',
                'color' => '#20604D',
                'title' => 'Guards! Guards!',
                'released' => '1989-10-01',
                'publisher' => 'Gollancz',
                'plot' => '"Guards! Guards!" è il primo romanzo della serie Discworld di Terry Pratchett. Segue le avventure della Guardia Cittadina di Ankh-Morpork mentre combattono contro una minaccia diabolica che minaccia la città.',
                'isbn' => 9780552134627,
                'author' => 18,
                'genre' => 3,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71orJPdTI+L._SY522_.jpg',
                'color' => '#3782C1',
                'title' => 'Mort',
                'released' => '1987-09-28',
                'publisher' => 'Gollancz',
                'plot' => '"Mort" è il quarto romanzo della serie Discworld. Racconta la storia di Mort, un giovane che diventa l\'apprendista della Morte stessa e si immerge in avventure stravaganti e comiche.',
                'isbn' => 9780552166628,
                'author' => 18,
                'genre' => 3,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/61+w0FHwm1L.jpg',
                'color' => '#84D3BC',
                'title' => 'Wyrd Sisters',
                'released' => '1988-11-24',
                'publisher' => 'Gollancz',
                'plot' => '"Wyrd Sisters" è il sesto romanzo della serie Discworld. Segue le streghe di Lancre mentre cercano di fermare una cospirazione pericolosa e proteggere il legittimo erede al trono.',
                'isbn' => 9780062225736,
                'author' => 18,
                'genre' => 3,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/8135QxIueIL._SL1500_.jpg',
                'color' => '#FEB879',
                'title' => 'Small Gods',
                'released' => '1992-06-11',
                'publisher' => 'Gollancz',
                'plot' => '"Small Gods" è un romanzo della serie Discworld che esplora temi di religione, potere e fede. Segue il dio Omnianismo, che si trova improvvisamente a vivere come un essere umano senza poteri divini.',
                'isbn' => 9780062237371,
                'author' => 18,
                'genre' => 3,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71JzdxMxqUL._SL1200_.jpg',
                'color' => '#DCC15D',
                'title' => 'The Colour of Magic',
                'released' => '1983-11-24',
                'publisher' => 'Colin Smythe Ltd',
                'plot' => '"The Colour of Magic" è il primo romanzo della serie Discworld. Presenta il turista Twoflower e il mago incompetente Rincewind mentre si imbarcano in un viaggio attraverso un mondo fantastico pieno di pericoli e avventure imprevedibili.',
                'isbn' => 9780552124758,
                'author' => 18,
                'genre' => 3,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71FMhb8InfL._SL1500_.jpg',
                'color' => '#9CCDEB',
                'title' => 'Le avventure di Tom Sawyer',
                'released' => '1876-12-01',
                'publisher' => 'Charles L. Webster And Company',
                'plot' => '"Le avventure di Tom Sawyer" è un romanzo scritto da Mark Twain. Racconta le vicende del giovane Tom Sawyer e dei suoi amici in una piccola città lungo il fiume Mississippi.',
                'isbn' => 9788854172411,
                'author' => 16,
                'genre' => 9,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/61ZmnyDEqwL._SL1500_.jpg',
                'color' => '#E88133',
                'title' => 'Le avventure di Huckleberry Finn',
                'released' => '1884-12-01',
                'publisher' => 'Charles L. Webster And Company',
                'plot' => '"Le avventure di Huckleberry Finn" è un romanzo di Mark Twain che segue le avventure di Huck Finn e del suo amico Jim, un ragazzo afroamericano, lungo il fiume Mississippi nell\'America prebellica.',
                'isbn' => 9788854172039,
                'author' => 16,
                'genre' => 7,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71hfdA0bW2L._SL1264_.jpg',
                'color' => '#845608',
                'title' => 'Il principe e il povero',
                'released' => '1881-12-01',
                'publisher' => 'James R. Osgood',
                'plot' => '"Il principe e il povero" è un romanzo storico di Mark Twain che narra la storia di due ragazzi, Tom Canty e il principe Edoardo, che scambiano le loro identità e vivono esperienze sorprendenti nel XVI secolo in Inghilterra.',
                'isbn' => 9788837039322,
                'author' => 16,
                'genre' => 1,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71i0DYh0EML._SL1464_.jpg',
                'color' => '#AA8860',
                'title' => 'La vita sul Mississippi',
                'released' => '1883-12-01',
                'publisher' => 'James R. Osgood',
                'plot' => '"La vita sul Mississippi" è un resoconto autobiografico di Mark Twain che narra le sue esperienze e avventure lungo il fiume Mississippi, esplorando la vita sul fiume e la cultura delle città lungo le sue sponde.',
                'isbn' => 9788804675894,
                'author' => 16,
                'genre' => 12,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/51tRurVlbnL.jpg',
                'color' => '#98C693',
                'title' => 'Il diario di Adamo ed Eva',
                'released' => '1904-12-01',
                'publisher' => 'Harper & Brothers',
                'plot' => '"Il diario di Adamo ed Eva" è una raccolta di racconti umoristici di Mark Twain che immagina la vita di Adamo ed Eva nel Giardino dell\'Eden e le loro prime esperienze nel mondo.',
                'isbn' => 9788804668711,
                'author' => 16,
                'genre' => 15,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81RARTnoWjL._SL1500_.jpg',
                'color' => '#9D3617',
                'title' => 'Norwegian Wood',
                'released' => '1987-08-04',
                'publisher' => 'Kodansha',
                'plot' => 'Toru Watanabe reflects on past relationships while living in Tokyo in the 1960s.',
                'isbn' => 9780375704024,
                'author' => 8,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81TLIfSiXsL._SL1500_.jpg',
                'color' => '#373F69',
                'title' => '1Q84',
                'released' => '2009-05-29',
                'publisher' => 'Shinchosha',
                'plot' => 'Aomame, a fitness instructor, and Tengo, an aspiring writer, become intertwined in a mysterious world.',
                'isbn' => 9780307593313,
                'author' => 8,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81tdbrewW0L._SL1500_.jpg',
                'color' => '#CD102E',
                'title' => 'Kafka on the Shore',
                'released' => '2002-09-12',
                'publisher' => 'Shinchosha',
                'plot' => 'Kafka Tamura runs away from home to escape a prophecy, intertwining with Nakata.',
                'isbn' => 9781400079278,
                'author' => 8,
                'genre' => 5,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/61RH4yUye+L._SL1500_.jpg',
                'color' => '#64a2eb',
                'title' => 'Le Notti Bianche',
                'released' => '1848-10-31',
                'publisher' => 'Penguin Books',
                'plot' => '"Notti bianche" è un\'opera magistrale di Fyodor Dostoevsky che cattura l\'essenza della solitudine e dell\'amore non corrisposto. Ambientato nella pittoresca San Pietroburgo, il racconto segue il protagonista, il Sognatore, un giovane idealista che vive nella sua immaginazione più che nel mondo reale.',
                'isbn' => 9780241619780,
                'author' => 13,
                'genre' => 5,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/81Pt2iJfagL._SL1500_.jpg',
                'color' => '#ce565f',
                'title' => 'Memorie dal sottosuolo',
                'released' => '1864-04-01',
                'publisher' => 'W W Norton & Co Inc',
                'plot' => 'Questo romanzo breve, pubblicato nel 1864, è una narrazione in prima persona delle riflessioni di un uomo alienato e cinico, conosciuto solo come "l\'Uomo del Sottosuolo". Il libro esplora le contraddizioni della natura umana e critica le idee razionaliste dell\'epoca.',
                'isbn' =>  9780393976120,
                'author' => 13,
                'genre' => 5,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/51evneDPTiL._SY445_SX342_.jpg',
                'color' => '#004a5d',
                'title' => 'L\'idiota',
                'released' => '1869-01-01',
                'publisher' => 'Rizzoli',
                'plot' => 'Pubblicato nel 1869, "L\'idiota" segue il principe Myshkin, un uomo gentile e altruista ma ingenuo, che torna in Russia dopo un periodo di cura in Svizzera. Il romanzo esplora il contrasto tra la bontà del principe Myshkin e la corruzione e la follia della società russa dell\'epoca.',
                'isbn' =>  9788817067959,
                'author' => 13,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/61g5fbi7rRL._SL1500_.jpg',
                'color' => '#85764f',
                'title' => 'Demoni',
                'released' => '1869-01-01',
                'publisher' => 'Feltrinelli',
                'plot' => '"Demoni" di Dostoevskij è un romanzo che esplora il nichilismo e la rivoluzione nella Russia provinciale degli anni \'60 del XIX secolo. Segue le vicende di un gruppo rivoluzionario guidato da Pyotr Stepanovich Verkhovensky e il ritorno misterioso e tormentato di Nikolai Stavrogin. ',
                'isbn' =>  9788807902475,
                'author' => 13,
                'genre' => 5,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/615r41Z1PEL._SL1500_.jpg',
                'color' => '#70695f',
                'title' => 'Delitto e Castigo',
                'released' => '1866-10-01',
                'publisher' => 'Feltrinelli',
                'plot' => '"Delitto e Castigo" di Dostoevskij è un romanzo che segue la storia di Rodion Raskolnikov, uno studente povero e alienato che commette un omicidio per giustificare la propria superiorità intellettuale.',
                'isbn' =>  9788807900617,
                'author' => 13,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81xd+qOvR3L._SL1500_.jpg',
                'color' => '#376779',
                'title' => 'Cent\'anni di solitudine',
                'released' => '1967-05-30',
                'publisher' => 'Editorial Sudamericana',
                'plot' => 'La saga della famiglia Buendía a Macondo, una città immaginaria, attraversa generazioni di amore, tragedia e mistero.',
                'isbn' => 9788804488302,
                'author' => 9,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81izfzodwkL._SL1500_.jpg',
                'color' => '#5B2981',
                'title' => 'L\'amore ai tempi del colera',
                'released' => '1985-11-06',
                'publisher' => 'Editorial Sudamericana',
                'plot' => 'La storia d\'amore tra Fermina Daza e Florentino Ariza, che attende per più di cinquant\'anni la sua occasione per essere realizzata.',
                'isbn' => 9788804677164,
                'author' => 9,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/91G3fHgUwoL._SL1500_.jpg',
                'color' => '#DD8123',
                'title' => 'Cronaca di una morte annunciata',
                'released' => '1981-08-30',
                'publisher' => 'Editorial La Oveja Negra',
                'plot' => 'Il racconto della morte annunciata di Santiago Nasar, narrato attraverso le testimonianze dei personaggi del villaggio.',
                'isbn' => 9788807818690,
                'author' => 9,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/813Tphs7WXL._SL1500_.jpg',
                'color' => '#697F6D',
                'title' => 'Guerra e pace',
                'released' => '1869-01-01',
                'publisher' => 'The Russian Messenger',
                'plot' => 'Una storia epica che segue le vite di diversi personaggi aristocratici durante l\'invasione di Napoleone in Russia e le conseguenti guerre napoleoniche.',
                'isbn' => 9788804464801,
                'author' => 10,
                'genre' => 1,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71DL12R0soL._SL1500_.jpg',
                'color' => '#846C2F',
                'title' => 'Anna Karenina',
                'released' => '1877-03-03',
                'publisher' => 'The Russian Messenger',
                'plot' => 'La storia di Anna Karenina e del suo tragico amore con il Conte Vronsky, ambientata nella società aristocratica della Russia imperiale.',
                'isbn' => 9788804668889,
                'author' => 10,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/61o-Cf3s4ML._SL1500_.jpg',
                'color' => '#494947',
                'title' => 'Resurrezione',
                'released' => '1899-01-01',
                'publisher' => 'Russian Messenger',
                'plot' => 'La storia di un uomo aristocratico che cerca il significato della vita e della redenzione attraverso il suo coinvolgimento con una donna contadina.',
                'isbn' => 9788804667783,
                'author' => 10,
                'genre' => 16,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/41C+6sFyhTL._SY445_SX342_.jpg',
                'color' => '#c0443a',
                'title' => 'La signora Dalloway',
                'released' => '1925-05-04',
                'publisher' => 'Feltrinelli',
                'plot' => 'Il romanzo segue la giornata della signora Clarissa Dalloway mentre si prepara per una festa serale nella Londra degli anni \'20. Attraverso un flusso di coscienza, il libro esplora le sue riflessioni interiori, così come quelle degli altri personaggi che incontra durante il giorno.',
                'isbn' =>  9788807900594,
                'author' => 11,
                'genre' => 5,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/61rGBNiqnrL._SL1500_.jpg',
                'color' => '#d8b784',
                'title' => 'Una stanza tutta per sé',
                'released' => '1924-10-24',
                'publisher' => 'Feltrinelli',
                'plot' => 'Un saggio che esplora le sfide che le donne affrontano nell\'ambiente letterario e sociale dell\'Inghilterra del XX secolo. Woolf sostiene la necessità per le donne di avere indipendenza economica e uno spazio personale per poter coltivare la propria creatività.',
                'isbn' =>  9788807900600,
                'author' => 11,
                'genre' => 5,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/71bO0+L2GsL._SL1500_.jpg',
                'color' => '#ea606d',
                'title' => 'Gli Anni',
                'released' => '1937-01-01',
                'publisher' => 'Feltrinelli',
                'plot' => 'Questo romanzo segue la famiglia Pargiter attraverso diverse generazioni, esplorando i cambiamenti sociali, politici e culturali che si verificano nel corso del tempo. La narrazione si concentra sui momenti significativi nella vita dei personaggi e sulle trasformazioni della società.',
                'isbn' =>  9788807901683,
                'author' => 11,
                'genre' => 5,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/619JF+bfGQL._SL1500_.jpg',
                'color' => '#bfc432',
                'title' => 'Gita al faro',
                'released' => '1927-01-01',
                'publisher' => 'Feltrinelli',
                'plot' => 'Questo romanzo segue la famiglia Ramsay durante due estati, esplorando le dinamiche familiari, le aspirazioni artistiche e i cambiamenti nel corso del tempo. La narrativa si concentra sulle percezioni dei personaggi e sulle loro riflessioni interiori.',
                'isbn' =>  9788811360889,
                'author' => 11,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/71FR4M7A69L._SL1500_.jpg',
                'color' => '#0FA42F',
                'title' => 'Padre Sergio',
                'released' => '1898-01-01',
                'publisher' => 'Russian Messenger',
                'plot' => 'La storia di un aristocratico che diventa un eremita dopo aver rifiutato una carriera ecclesiastica, ma deve affrontare le tentazioni della vita mondana.',
                'isbn' => 9788804633206,
                'author' => 10,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/81Iv8PVk3IL._SL1500_.jpg',
                'color' => '#B0BD59',
                'title' => 'La felicità coniugale',
                'released' => '1859-01-01',
                'publisher' => 'The Russian Messenger',
                'plot' => 'Un racconto che esplora le sfide e le gioie del matrimonio attraverso le vite di due coppie.',
                'isbn' => 9788804668834,
                'author' => 10,
                'genre' => 5,
            ],
        [
                'cover' => 'https://m.media-amazon.com/images/I/91nqU4TBlwL._SL1500_.jpg',
                'color' => '#5C7468',
                'title' => 'Del amor y otros demonios',
                'released' => '1994-11-01',
                'publisher' => 'Alfaguara',
                'plot' => 'La storia di un amore proibito tra una giovane eroina e un prete, ambientata nell\'America coloniale.',
                'isbn' => 9788804492347,
                'author' => 9,
                'genre' => 5,
            ],
            [
                'cover' => 'https://m.media-amazon.com/images/I/61r+8O8eN7L._SL1142_.jpg',
                'color' => '#BBF3D3',
                'title' => 'La mala hora',
                'released' => '1962-01-01',
                'publisher' => 'Editorial Sudamericana',
                'plot' => 'Un romanzo che esplora le tensioni e le violenze politiche in un piccolo villaggio colombiano.',
                'isbn' => 9780140157543,
                'author' => 9,
                'genre' => 15,
            ],
        [
                "cover" => "https://m.media-amazon.com/images/I/711S0A8NerL._SL1500_.jpg",
                "color" => "#902910",
                "title" => "L'elefante scomparso",
                "released" => "1993-08-01",
                "publisher" => "Einaudi",
                "plot" => "Un uomo parte per un viaggio alla ricerca di un elefante scomparso.",
                "isbn" => 9788806139122,
                "author" => 8,
                "genre" => 5
            ],
            [
                "cover" => "https://m.media-amazon.com/images/I/714faCtxlBL._SL1500_.jpg",
                "color" => "#8D1B0A",
                "title" => "Dance Dance Dance",
                "released" => "1994-04-01",
                "publisher" => "Einaudi",
                "plot" => "Un uomo va alla ricerca di una donna scomparsa, incontrando misteri lungo il cammino.",
                "isbn" => 9788806122919,
                "author" => 8,
                "genre" => 5
            ],
            [
                "cover" => "https://m.media-amazon.com/images/I/613iJw64zoL._SL1198_.jpg",
                "color" => "#DEE341",
                "title" => "Lullaby",
                "released" => "2002-09-10",
                "publisher" => "Mondadori",
                "plot" => "Un giornalista scopre un canto letale che uccide chiunque lo ascolti.",
                "isbn" => 9788804501537,
                "author" => 19,
                "genre" => 5
            ],
            [
                "cover" => "https://m.media-amazon.com/images/I/7110hV6iUdL._SL1500_.jpg",
                "color" => "#BE4E88",
                "title" => "Fight Club",
                "released" => "1996-06-21",
                "publisher" => "Mondadori",
                "plot" => "Un uomo insoddisfatto crea un club di combattimento segreto.",
                "isbn" => 9788804448666,
                "author" => 19,
                "genre" => 5
            ],
            [
                "cover" => "https://m.media-amazon.com/images/I/31F6CiYIMiL.jpg",
                "color" => "#F5B93B",
                "title" => "Survivor",
                "released" => "2000-02-22",
                "publisher" => "Mondadori",
                "plot" => "Un superstite di un culto religioso diventa una celebrità.",
                "isbn" => 9788804487009,
                "author" => 19,
                "genre" => 5
            ],
        [
            "cover" => "https://m.media-amazon.com/images/I/61yp7ska-jL._SL1154_.jpg",
            "color" => "#572157",
            "title" => "Invisible Monsters",
            "released" => "1999-09-17",
            "publisher" => "W. W. Norton & Company",
            "plot" => "Una modella sfigurata cerca vendetta in un mondo di apparenze superficiali.",
            "isbn" => 9780393319293,
            "author" => 19,
            "genre" => 5
        ],
        [
            "cover" => "https://m.media-amazon.com/images/I/71B4cpGdNjL._SL1388_.jpg",
            "color" => "#C03C27",
            "title" => "Soffocare",
            "released" => "2001-05-22",
            "publisher" => "Anchor Books",
            "plot" => "Un uomo cerca di sostenere la madre malata simulando soffocamenti nei ristoranti.",
            "isbn" => 9780385720922,
            "author" => 19,
            "genre" => 5
        ],
        

            [
                'cover' => 'https://m.media-amazon.com/images/I/51ykNaEDBBL._SY445_SX342_.jpg',
                'color' => '#35392e',
                'title' => 'Ragione e sentimento',
                'released' => '1881-01-01',
                'publisher' => 'Feltrinelli',
                'plot' => 'Le due sorelle Dashwood, Elinor e Marianne, si trovano ad affrontare sfide finanziarie e sentimentali dopo la morte del padre. Il romanzo esplora il contrasto tra razionalità e sensibilità attraverso le prospettive delle due sorelle mentre navigano tra amori complicati e aspirazioni sociali.',
                'isbn' =>   9788807900112,
                'author' => 2,
                'genre' => 5,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/717-E0jJ36L._SL1480_.jpg',
                'color' => '#a6cfc9',
                'title' => 'Northanger Abbey',
                'released' => '1817-12-01',
                'publisher' => 'Feltrinelli',
                'plot' => '"Northanger Abbey" è un romanzo che mette in scena Catherine Morland, una giovane donna ingenua e amante dei romanzi gotici, che visita la residenza di Northanger Abbey. Qui, Catherine si trova coinvolta in un intreccio di inganni e malintesi mentre cerca di adattare la sua visione romantica del mondo alla realtà.',
                'isbn' =>   9788845297021,
                'author' => 2,
                'genre' => 5,
            ],

            [
                'cover' => 'https://m.media-amazon.com/images/I/61Iw-AiW+RL._SL1500_.jpg',
                'color' => '#000000',
                'title' => 'Faust',
                'released' => '1829-01-19',
                'publisher' => 'Mondadori',
                'plot' => '"Faust" di Johann Wolfgang von Goethe è una tragedia in cui il dottor Faust, disilluso e assetato di conoscenza, fa un patto con il diavolo Mefistofele per ottenere saggezza e piacere terreni. ',
                'isbn' =>   9788804670827,
                'author' => 20,
                'genre' => 5,
            ],
            [
                "cover" => "https://m.media-amazon.com/images/I/61IljYs0TzL._SL1187_.jpg",
                "color" => "#834B71",
                "title" => "La metamorfosi",
                "released" => "1915-10-15",
                "publisher" => "Kurt Wolff Verlag",
                "plot" => "Gregor Samsa si sveglia trasformato in un insetto e deve affrontare l'emarginazione familiare.",
                "isbn" => 9788806210616,
                "author" => 12,
                "genre" => 5
            ],
            [
                "cover" => "https://m.media-amazon.com/images/I/61xUwVMgfqL._SL1500_.jpg",
                "color" => "#B3602E",
                "title" => "Il processo",
                "released" => "1925-04-26",
                "publisher" => "S. Fischer Verlag",
                "plot" => "Josef K. viene arrestato e intraprende una disperata ricerca di giustizia in un mondo incomprensibile.",
                "isbn" => 9788806214522,
                "author" => 12,
                "genre" => 5
            ],
            [
                "cover" => "https://m.media-amazon.com/images/I/8157zXUmcvL._SL1500_.jpg",
                "color" => "#255959",
                "title" => "Il castello",
                "released" => "1926-06-25",
                "publisher" => "S. Fischer Verlag",
                "plot" => "K. si scontra con l'apparato burocratico del castello mentre cerca di ottenere risposte alle sue domande.",
                "isbn" => 9788806249340,
                "author" => 12,
                "genre" => 5
            ],
            [
                "cover" => "https://m.media-amazon.com/images/I/810pEFFkQRL._SL1192_.jpg",
                "color" => "#CC071E",
                "title" => "America",
                "released" => "1927-06-22",
                "publisher" => "S. Fischer Verlag",
                "plot" => "Karl Rossman, esiliato in America, cerca fortuna mentre naviga attraverso un mondo di opportunità e corruzione.",
                "isbn" => 9788806203175,
                "author" => 12,
                "genre" => 5
            ],
            [
                "cover" => "https://m.media-amazon.com/images/I/61VBlnfWH+L._SL1254_.jpg",
                "color" => "#85BC8C",
                "title" => "La colonia penale",
                "released" => "1919-10-31",
                "publisher" => "Die Schmiede",
                "plot" => "Un ufficiale si imbatte in una colonia penale brutalmente punitiva, interrogando la moralità e la giustizia.",
                "isbn" => 9788806210609,
                "author" => 12,
                "genre" => 5
            ],
        


 ];


        foreach ($libri as $libro) {
            Book::create($libro);
        }
    }
}
